coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 70%
ignore:
  - "testenv/**"
  - "scripts/**"
  - "docs/**"
  - "wiki/**"
  - "**/*_mock.go"
  - "main.go"

comment:
  layout: "header, diff, flags, files"
  require_changes: true
