object ApiListener "api" {
  cert_path = "/data/var/lib/icinga2/certs/icinga2.crt"
  key_path  = "/data/var/lib/icinga2/certs/icinga2.key"
  ca_path   = "/data/var/lib/icinga2/certs/ca.crt"

  bind_port      = 5665
  accept_config  = true
  accept_commands = true
}
