// Default host (container itself)
object Host NodeName {
  import "generic-host"
  address = "127.0.0.1"
  address6 = "::1"
  vars.os = "Linux"
}

// Test host for webhook-bridge dummy services
object Host "test-host" {
  import "generic-host"
  address = "127.0.0.1"
  display_name = "Test Host - webhook-bridge dev"
  vars.os = "Linux"
}
