apply Notification "iaf-mail-service" to Service {
  import "mail-service-notification"

  interval = 0s

  if (host.vars.notification.users) {
    users = host.vars.notification.users
  }
  if (host.vars.notification.user_groups) {
    user_groups = host.vars.notification.user_groups
  } else if (host.vars.notification.groups) {
    user_groups = host.vars.notification.groups
  }
  if (host.vars.notification.service_states) {
    var service_states = []
    if ("ok" in host.vars.notification.service_states) {
      service_states += [ OK ]
    }
    if ("warning" in host.vars.notification.service_states) {
      service_states += [ Warning ]
    }
    if ("critical" in host.vars.notification.service_states) {
      service_states += [ Critical ]
    }
    if ("unknown" in host.vars.notification.service_states) {
      service_states += [ Unknown ]
    }
    if (len(service_states) > 0) {
      states = service_states
    }
  }

  assign where host.vars.notification && (host.vars.notification.users || host.vars.notification.groups || host.vars.notification.user_groups)
}

apply Notification "iaf-mail-host" to Host {
  import "mail-host-notification"

  interval = 0s

  if (host.vars.notification.users) {
    users = host.vars.notification.users
  }
  if (host.vars.notification.user_groups) {
    user_groups = host.vars.notification.user_groups
  } else if (host.vars.notification.groups) {
    user_groups = host.vars.notification.groups
  }
  if (host.vars.notification.host_states) {
    var host_states = []
    if ("up" in host.vars.notification.host_states) {
      host_states += [ Up ]
    }
    if ("down" in host.vars.notification.host_states) {
      host_states += [ Down ]
    }
    if (len(host_states) > 0) {
      states = host_states
    }
  }

  assign where host.vars.notification && (host.vars.notification.users || host.vars.notification.groups || host.vars.notification.user_groups)
}
