object User "icingaadmin" {
  import "generic-user"
  display_name = "Icinga Admin"
  email = "icingaadmin@example.test"
}

object User "alpha" {
  import "generic-user"
  display_name = "Alpha"
  email = "alpha@example.test"
}

object User "omega" {
  import "generic-user"
  display_name = "Omega"
  email = "omega@example.test"
}

object User "beta" {
  import "generic-user"
  display_name = "Beta"
  email = "beta@example.test"
}

object User "ceta" {
  import "generic-user"
  display_name = "Ceta"
  email = "ceta@example.test"
}
